---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - wget https://raw.githubusercontent.com/ansible/galaxy/devel/galaxy/importer/linters/yamllint.yaml
  - ansible-lint tasks/main.yml
  - yamllint -c yamllint.yaml tasks/main.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -b -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
